apiVersion: v1
kind: Service
metadata:
  name: podinfo
  namespace: dev
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 9898
      protocol: TCP
      name: http
  selector:
    app: podinfo

---
apiVersion: v1
kind: Service
metadata:
  name: podinfo-lb
  namespace: dev
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9898
      protocol: TCP
      name: http
  selector:
    app: podinfo

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: podinfo
  namespace: dev
  annotations:
    flux.weave.works/tag.podinfod: glob:*
    flux.weave.works/automated: 'true'
spec:
  replicas: 4
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: podinfod
        image: quay.io/brice/metrics-demo
        command:
        - ./podinfo
        - --port=9898
        ports:
        - containerPort: 9898
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9898
          initialDelaySeconds: 1
          periodSeconds: 5
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9898
          initialDelaySeconds: 1
          periodSeconds: 10
          failureThreshold: 2
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
  creationTimestamp: null
  name: podinfo
  namespace: dev
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: podinfo
          servicePort: 9898
          port: http
        path: /podinfo
status:
  loadBalancer: {}
